menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
     - id: about # 页面中高亮的 menu_id
       theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
#       icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
       title: 关于 # 标题
       url: /about # 跳转链接，支持相对路径和绝对路径
     - id: friends
       theme: '#1BCDFC'
    #   icon: solar:notebook-bookmark-bold-duotone
       title: 友情链接
       url: /friends
     - id: contact
       theme: '#1BCDFC'
    #   icon: solar:planet-bold-duotone
       title: 联系方式
       url: /contact
     - id: sub
       theme: '#1BCDFC'
    #   icon: solar:chat-square-like-bold-duotone
       title: 订阅
       url: /sub
     - id: buymeatea
       theme: '#1BCDFC'
       title: 打赏
       url: /buymeatea

inject:
  head:
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-web/style.css" />
    - <link rel="preconnect" href="https://fonts.bunny.net">
    - <link href="https://fonts.bunny.net/css?family=pt-mono:400" rel="stylesheet" />
style:
  font-family:
    logo: 'LXGW WenKai Screen'
    body: 'LXGW WenKai Screen'
    code: 'PT Mono'
    codeblock: 'PT Mono'
comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: devkamiki/obsp
    data-repo-id: R_kgDOOJXv_g
    data-category: Announcements
    data-category-id: DIC_kwDOOJXv_s4CoGLJ
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous
